sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  md5:
    salt: itheima
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI4GKKRZkaZk3FxcP9fiuZ
    access-key-secret: rkPgyyNqCFmXraP0xJTf4hB19zSQwC
    bucket-name: itheima190
  redis:
    host: localhost
    port: 6379
    password: 123456
  wechat:
#    appid: wxa4fc931181ecc92b
#    secret: a6bccc2c3b60686e8e7feb2d78b0f1f4
    appid: wxffb3637a228223b8
    secret: 84311df9199ecacdf4f12d27b6b9522d
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\weixin\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\weixin\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://2d05fd75.r12.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://2d05fd75.r12.cpolar.top/notify/refundSuccess
  shop:
    address: 广州市天河区珠吉路58号
  baidu:
    ak: svtU5Y6kI0ur0yiqVrS0LXAd4bfo4NM4
